services:
    Cisse\Bundle\Ui\DataCollector\UiComponentDataCollector:
        arguments:
            $profile: '@twig.profile'
        tags:
            - name: data_collector
              template: '@ui/data_collector/ui_components.html.twig'
              id: ui_components
              priority: 280
